# Generated by Django 5.0.2 on 2025-10-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="notes",
            new_name="comment",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("confirmed", "Подтверждено"),
                    ("completed", "Выполнено"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
