# Generated by Django 5.0.2 on 2025-10-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_options_alter_appointment_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
