# Generated by Django 5.0.2 on 2025-10-28 22:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_delete_appointment'),
        ('services', '0002_servicecategory_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_date', models.DateField(verbose_name='Желаемая дата')),
                ('desired_time', models.CharField(choices=[('08:00', '08:00 - 08:30'), ('08:30', '08:30 - 09:00'), ('09:00', '09:00 - 09:30'), ('09:30', '09:30 - 10:00'), ('10:00', '10:00 - 10:30'), ('10:30', '10:30 - 11:00'), ('11:00', '11:00 - 11:30'), ('11:30', '11:30 - 12:00'), ('12:00', '12:00 - 12:30'), ('12:30', '12:30 - 13:00'), ('13:00', '13:00 - 13:30'), ('13:30', '13:30 - 14:00'), ('14:00', '14:00 - 14:30'), ('14:30', '14:30 - 15:00'), ('15:00', '15:00 - 15:30'), ('15:30', '15:30 - 16:00'), ('16:00', '16:00 - 16:30'), ('16:30', '16:30 - 17:00'), ('17:00', '17:00 - 17:30'), ('17:30', '17:30 - 18:00'), ('18:00', '18:00 - 18:30'), ('18:30', '18:30 - 19:00'), ('19:00', '19:00 - 19:30'), ('19:30', '19:30 - 20:00')], max_length=5, verbose_name='Желаемое время')),
                ('status', models.CharField(choices=[('pending', 'Ожидание подтверждения'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], default='pending', max_length=20, verbose_name='Статус')),
                ('patient_name', models.CharField(max_length=200, verbose_name='Имя пациента')),
                ('patient_phone', models.CharField(max_length=20, verbose_name='Телефон пациента')),
                ('patient_email', models.EmailField(max_length=254, verbose_name='Email пациента')),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст пациента')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
                'ordering': ['-desired_date', 'desired_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('recommendations', models.TextField(verbose_name='Рекомендации')),
                ('prescription', models.TextField(blank=True, verbose_name='Назначения')),
                ('results_file', models.FileField(blank=True, null=True, upload_to='appointment_results/', verbose_name='Файл с результатами')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='appointments.appointment', verbose_name='Запись на прием')),
            ],
            options={
                'verbose_name': 'Результат приема',
                'verbose_name_plural': 'Результаты приемов',
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('desired_date', 'desired_time'), name='unique_appointment_time'),
        ),
    ]
