# Generated by Django 5.0.2 on 2025-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="URL"
            ),
        ),
    ]
