# Generated by Django 5.0.2 on 2025-11-03 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_service_slug_alter_servicecategory_slug"),
    ]

    operations = []
