# Generated by Django 5.0.6 on 2025-11-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_servicecategory_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="URL"
            ),
        ),
    ]
