# Generated by Django 5.0.6 on 2025-11-01 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_alter_service_slug_alter_servicecategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Цена",
            ),
        ),
    ]
